In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies = movies.merge(credits, on='title')

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
movies = movies[['movie_id', 'title','overview','genres','keywords','cast','crew']]

In [8]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
import ast

In [10]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

In [11]:
movies.dropna(inplace=True)

In [12]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [15]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [17]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [18]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [19]:
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
2770,107811,21 & Over,Brilliant student Jeff Chang has the most impo...,[Comedy],"[alcohol, birthday, debauchery]","[Miles Teller, Skylar Astin, Justin Chon]","[Jon Lucas, Scott Moore]"
3767,184345,A Haunted House 2,"Having exorcised the demons of his ex, Malcolm...","[Comedy, Horror]",[haunted house],"[Marlon Wayans, Jaime Pressly, Essence Atkins]",[Michael Tiddes]
4044,7512,Idiocracy,To test its top-secret Human Hibernation Proje...,"[Adventure, Comedy, Science Fiction]","[prostitute, capitalism, usa president, arena,...","[Luke Wilson, Maya Rudolph, Dax Shepard]",[Mike Judge]
3219,9451,Election,A high school teacher's personal life becomes ...,[Comedy],"[jealousy, infidelity, vandalism, museum, mote...","[Matthew Broderick, Reese Witherspoon, Chris K...",[Alexander Payne]
2079,19255,Away We Go,Verona and Burt have moved to Colorado to be c...,"[Drama, Comedy, Romance]","[interracial relationship, dead father, refere...","[John Krasinski, Maya Rudolph, Carmen Ejogo]",[Sam Mendes]

In [20]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [21]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [23]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [24]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [25]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])

In [26]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [28]:
vector = cv.fit_transform(new['tags']).toarray()

In [29]:
vector.shape

(4806, 5000)

In [30]:
from sklearn.metrics.pairwise import cosine_similarity

In [31]:
similarity = cosine_similarity(vector)

In [32]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])

[(0, np.float64(0.9999999999999998)),
 (539, np.float64(0.2537477434955704)),
 (1192, np.float64(0.25112360116696136)),
 (260, np.float64(0.2442250043490654)),
 (1214, np.float64(0.24260844762468367)),
 (507, np.float64(0.24165612634006073)),
 (582, np.float64(0.2372894989381248)),
 (1440, np.float64(0.2372894989381248)),
 (1202, np.float64(0.2369241569216954)),
 (1916, np.float64(0.23394386020951635)),
 (3728, np.float64(0.2324952774876386)),
 (74, np.float64(0.22305671869347438)),
 (322, np.float64(0.21919864974047634)),
 (3606, np.float64(0.21775177815467112)),
 (83, np.float64(0.21582051197002577)),
 (4190, np.float64(0.2152488010002526)),
 (2329, np.float64(0.2113701265354594)),
 (2405, np.float64(0.21059925059706255)),
 (47, np.float64(0.21049133398705727)),
 (61, np.float64(0.21029989116983447)),
 (495, np.float64(0.21029989116983447)),
 (972, np.float64(0.2101050788156825)),
 (2969, np.float64(0.2071841649822589)),
 (942, np.float64(0.20668850837512243)),
 (1327, np.float64(0.2056773510573183)),
 (466, np.float64(0.20567735105731827)),
 (2200, np.float64(0.20032733246124987)),
 (973, np.float64(0.1973593560521103)),
 (1199, np.float64(0.19727878476642874)),
 (151, np.float64(0.19374606457303215)),
 (1273, np.float64(0.19344776406574832)),
 (4046, np.float64(0.1926263261127128)),
 (3160, np.float64(0.18983159915049982)),
 (4405, np.float64(0.18983159915049982)),
 (2782, np.float64(0.1898315991504998)),
 (461, np.float64(0.18857857160117855)),
 (305, np.float64(0.18790823039834775)),
 (1533, np.float64(0.18668326147193276)),
 (931, np.float64(0.18641092980036)),
 (150, np.float64(0.18494886071852695)),
 (3536, np.float64(0.18427434427242972)),
 (1319, np.float64(0.18380365552345193)),
 (3325, np.float64(0.18380365552345193)),
 (27, np.float64(0.1823843010350213)),
 (2997, np.float64(0.1823843010350213)),
 (300, np.float64(0.18195633571851272)),
 (220, np.float64(0.18009006755629928)),
 (1069, np.float64(0.1797236580870839)),
 (36, np.float64(0.17972365808708385)),
 (4, np.float64(0.17757120130114434)),
 (184, np.float64(0.17757120130114434)),
 (67, np.float64(0.1771615786072478)),
 (301, np.float64(0.17684493567566834)),
 (373, np.float64(0.1752499093081954)),
 (46, np.float64(0.17170914210964275)),
 (7, np.float64(0.17155007848855516)),
 (2492, np.float64(0.17139779254776524)),
 (2727, np.float64(0.17139779254776524)),
 (1827, np.float64(0.1696751579473019)),
 (1342, np.float64(0.16916516233038026)),
 (149, np.float64(0.16702953813186466)),
 (26, np.float64(0.16673100431301852)),
 (1804, np.float64(0.16673100431301852)),
 (661, np.float64(0.16569860426698665)),
 (108, np.float64(0.1643989873053573)),
 (208, np.float64(0.1643989873053573)),
 (838, np.float64(0.1643989873053573)),
 (4008, np.float64(0.1643989873053573)),
 (94, np.float64(0.16120647005479025)),
 (581, np.float64(0.16120647005479025)),
 (2511, np.float64(0.16120647005479025)),
 (52, np.float64(0.1600142241187995)),
 (1392, np.float64(0.15958626340564364)),
 (31, np.float64(0.15819299929208316)),
 (1295, np.float64(0.15794943794779692)),
 (1379, np.float64(0.15794943794779692)),
 (4336, np.float64(0.1559625734730109)),
 (91, np.float64(0.1553424415003)),
 (168, np.float64(0.15404884978892902)),
 (3352, np.float64(0.1526406277181659)),
 (311, np.float64(0.1522038868295523)),
 (1961, np.float64(0.15110651212172094)),
 (577, np.float64(0.15007505629691606)),
 (3626, np.float64(0.15007505629691606)),
 (158, np.float64(0.1487044791289829)),
 (502, np.float64(0.1487044791289829)),
 (1176, np.float64(0.14763464883937316)),
 (1353, np.float64(0.14704292441876157)),
 (172, np.float64(0.14704292441876154)),
 (490, np.float64(0.14704292441876154)),
 (17, np.float64(0.1461508458653816)),
 (1934, np.float64(0.1454358496691159)),
 (111, np.float64(0.1453095484297741)),
 (2165, np.float64(0.1453095484297741)),
 (422, np.float64(0.14349920066683505)),
 (505, np.float64(0.14349920066683505)),
 (1484, np.float64(0.14349920066683505)),
 (41, np.float64(0.14237369936287486)),
 (84, np.float64(0.14165281524036175)),
 (369, np.float64(0.14097096860865022)),
 (557, np.float64(0.14097096860865022)),
 (568, np.float64(0.14097096860865022)),
 (2682, np.float64(0.14097096860865022)),
 (56, np.float64(0.14019992744655632)),
 (249, np.float64(0.14019992744655632)),
 (1325, np.float64(0.14019992744655632)),
 (2580, np.float64(0.14019992744655632)),
 (1320, np.float64(0.13949716649258315)),
 (332, np.float64(0.1389425035941821)),
 (1218, np.float64(0.1389425035941821)),
 (487, np.float64(0.1371182340382122)),
 (187, np.float64(0.13699915608779772)),
 (1669, np.float64(0.13678822577626598)),
 (2129, np.float64(0.13678822577626598)),
 (4348, np.float64(0.13678822577626598)),
 (2869, np.float64(0.13678822577626595)),
 (413, np.float64(0.13513513513513514)),
 (1941, np.float64(0.13513513513513514)),
 (2616, np.float64(0.1342312110428049)),
 (4490, np.float64(0.1342312110428049)),
 (342, np.float64(0.13377695860286035)),
 (595, np.float64(0.13334518676566626)),
 (1013, np.float64(0.13334518676566626)),
 (3407, np.float64(0.13334518676566626)),
 (3620, np.float64(0.13334518676566626)),
 (127, np.float64(0.13200500012082497)),
 (2476, np.float64(0.13181243254912406)),
 (1475, np.float64(0.1316245316231641)),
 (68, np.float64(0.13151918984428584)),
 (134, np.float64(0.13151918984428584)),
 (368, np.float64(0.13151918984428584)),
 (1156, np.float64(0.13151918984428584)),
 (2968, np.float64(0.13151918984428584)),
 (754, np.float64(0.12996881122750908)),
 (3671, np.float64(0.12996881122750908)),
 (1000, np.float64(0.12951986753290365)),
 (1045, np.float64(0.1289651760438322)),
 (1094, np.float64(0.1289651760438322)),
 (1654, np.float64(0.1289651760438322)),
 (2374, np.float64(0.1289651760438322)),
 (3374, np.float64(0.1289651760438322)),
 (3997, np.float64(0.1289651760438322)),
 (740, np.float64(0.1283740414907742)),
 (1613, np.float64(0.1283740414907742)),
 (1711, np.float64(0.12734290799340264)),
 (529, np.float64(0.12683657235796025)),
 (778, np.float64(0.12683657235796025)),
 (1035, np.float64(0.12683657235796025)),
 (483, np.float64(0.12655439943366653)),
 (420, np.float64(0.12535305264097507)),
 (1297, np.float64(0.12535305264097507)),
 (1737, np.float64(0.12527215359889848)),
 (939, np.float64(0.12427395320024)),
 (1743, np.float64(0.12427395320024)),
 (1829, np.float64(0.12427395320024)),
 (228, np.float64(0.12392039927415242)),
 (278, np.float64(0.12392039927415242)),
 (2709, np.float64(0.12392039927415242)),
 (3307, np.float64(0.12392039927415242)),
 (3405, np.float64(0.12392039927415242)),
 (1571, np.float64(0.12329924047901797)),
 (3216, np.float64(0.12329924047901797)),
 (2543, np.float64(0.12253577034896797)),
 (28, np.float64(0.1221125021745327)),
 (275, np.float64(0.1221125021745327)),
 (1272, np.float64(0.1221125021745327)),
 (2071, np.float64(0.1221125021745327)),
 (4673, np.float64(0.1221125021745327)),
 (454, np.float64(0.12119654139092992)),
 (549, np.float64(0.12119654139092992)),
 (95, np.float64(0.1211965413909299)),
 (432, np.float64(0.1211965413909299)),
 (238, np.float64(0.12050719759100866)),
 (72, np.float64(0.12006004503753284)),
 (579, np.float64(0.12006004503753284)),
 (1978, np.float64(0.12006004503753284)),
 (2864, np.float64(0.12006004503753284)),
 (1508, np.float64(0.11990028442779209)),
 (624, np.float64(0.11961783342433499)),
 (653, np.float64(0.11961783342433499)),
 (808, np.float64(0.11961783342433499)),
 (4201, np.float64(0.11961783342433499)),
 (3145, np.float64(0.11874787399915188)),
 (50, np.float64(0.11810771907149853)),
 (692, np.float64(0.1174278480752552)),
 (1275, np.float64(0.11742784807525519)),
 (3628, np.float64(0.11742784807525519)),
 (1570, np.float64(0.1162476387438193)),
 (123, np.float64(0.11624763874381927)),
 (166, np.float64(0.11624763874381927)),
 (169, np.float64(0.11624763874381927)),
 (232, np.float64(0.11624763874381927)),
 (294, np.float64(0.11624763874381927)),
 (687, np.float64(0.11624763874381927)),
 (859, np.float64(0.11624763874381927)),
 (1612, np.float64(0.11624763874381927)),
 (5, np.float64(0.11510231387903269)),
 (10, np.float64(0.1144727614064285)),
 (87, np.float64(0.1144727614064285)),
 (1029, np.float64(0.1144727614064285)),
 (2579, np.float64(0.1144727614064285)),
 (3006, np.float64(0.1144727614064285)),
 (199, np.float64(0.1139901881468883)),
 (81, np.float64(0.11389895949029986)),
 (627, np.float64(0.11314714296070713)),
 (1299, np.float64(0.11314714296070713)),
 (2255, np.float64(0.11314714296070713)),
 (2319, np.float64(0.11314714296070713)),
 (3719, np.float64(0.11314714296070713)),
 (3998, np.float64(0.11314714296070713)),
 (4016, np.float64(0.11314714296070713)),
 (126, np.float64(0.11277677488692017)),
 (508, np.float64(0.11277677488692017)),
 (777, np.float64(0.11185934253567072)),
 (14, np.float64(0.11115400287534567)),
 (854, np.float64(0.11115400287534567)),
 (900, np.float64(0.11115400287534567)),
 (1193, np.float64(0.11115400287534567)),
 (2009, np.float64(0.11115400287534567)),
 (2446, np.float64(0.11115400287534567)),
 (3496, np.float64(0.11115400287534567)),
 (1017, np.float64(0.11083777463036817)),
 (1369, np.float64(0.11028219331407116)),
 (1520, np.float64(0.11028219331407116)),
 (1717, np.float64(0.11028219331407116)),
 (1723, np.float64(0.11028219331407116)),
 (2630, np.float64(0.11028219331407116)),
 (3659, np.float64(0.11028219331407116)),
 (4133, np.float64(0.11028219331407116)),
 (18, np.float64(0.1098436937909367)),
 (1493, np.float64(0.1098436937909367)),
 (2102, np.float64(0.1098436937909367)),
 (2435, np.float64(0.1098436937909367)),
 (2756, np.float64(0.1098436937909367)),
 (513, np.float64(0.10959932487023819)),
 (1080, np.float64(0.10959932487023819)),
 (1292, np.float64(0.10959932487023819)),
 (3338, np.float64(0.10959932487023819)),
 (3618, np.float64(0.10959932487023819)),
 (4095, np.float64(0.10959932487023819)),
 (102, np.float64(0.10887588907733556)),
 (131, np.float64(0.10810810810810811)),
 (174, np.float64(0.10810810810810811)),
 (266, np.float64(0.10810810810810811)),
 (330, np.float64(0.10810810810810811)),
 (2068, np.float64(0.10810810810810811)),
 (3100, np.float64(0.10810810810810811)),
 (4077, np.float64(0.10810810810810811)),
 (403, np.float64(0.10793322294408637)),
 (141, np.float64(0.1076244005001263)),
 (3053, np.float64(0.1076244005001263)),
 (3779, np.float64(0.1076244005001263)),
 (3837, np.float64(0.1076244005001263)),
 (233, np.float64(0.10762440050012628)),
 (325, np.float64(0.10762440050012628)),
 (773, np.float64(0.10762440050012628)),
 (1154, np.float64(0.10762440050012628)),
 (3952, np.float64(0.10762440050012628)),
 (295, np.float64(0.106676149412533)),
 (312, np.float64(0.106676149412533)),
 (535, np.float64(0.106676149412533)),
 (2177, np.float64(0.106676149412533)),
 (4228, np.float64(0.106676149412533)),
 (182, np.float64(0.10529962529853128)),
 (986, np.float64(0.10529962529853128)),
 (139, np.float64(0.10524566699352861)),
 (4545, np.float64(0.10524566699352861)),
 (105, np.float64(0.10514994558491725)),
 (476, np.float64(0.10514994558491725)),
 (2452, np.float64(0.10514994558491725)),
 (2517, np.float64(0.10514994558491725)),
 (2558, np.float64(0.10514994558491725)),
 (2758, np.float64(0.10514994558491725)),
 (4196, np.float64(0.10514994558491725)),
 (4623, np.float64(0.10514994558491725)),
 (334, np.float64(0.10397504898200727)),
 (643, np.float64(0.10397504898200727)),
 (898, np.float64(0.10397504898200727)),
 (1054, np.float64(0.10397504898200727)),
 (3781, np.float64(0.10397504898200727)),
 (239, np.float64(0.10356162766686666)),
 (85, np.float64(0.10283867552865915)),
 (157, np.float64(0.10283867552865915)),
 (33, np.float64(0.10283867552865913)),
 (148, np.float64(0.10283867552865913)),
 (715, np.float64(0.10283867552865913)),
 (935, np.float64(0.10283867552865913)),
 (1278, np.float64(0.10283867552865913)),
 (1497, np.float64(0.10283867552865913)),
 (2656, np.float64(0.10283867552865913)),
 (4331, np.float64(0.10283867552865913)),
 (129, np.float64(0.10269923319261937)),
 (510, np.float64(0.10269923319261937)),
 (1107, np.float64(0.10269923319261937)),
 (3441, np.float64(0.10269923319261937)),
 (307, np.float64(0.1017387650221051)),
 (279, np.float64(0.10146925788636821)),
 (1084, np.float64(0.10146925788636821)),
 (1231, np.float64(0.10146925788636821)),
 (1271, np.float64(0.10146925788636821)),
 (2592, np.float64(0.10146925788636821)),
 (3462, np.float64(0.10146925788636821)),
 (4043, np.float64(0.10146925788636821)),
 (35, np.float64(0.10067340828210367)),
 (263, np.float64(0.10067340828210367)),
 (400, np.float64(0.10067340828210367)),
 (660, np.float64(0.10067340828210367)),
 (781, np.float64(0.10067340828210367)),
 (920, np.float64(0.10067340828210367)),
 (1304, np.float64(0.10067340828210367)),
 (1938, np.float64(0.10067340828210367)),
 (2657, np.float64(0.10067340828210367)),
 (4254, np.float64(0.10067340828210367)),
 (270, np.float64(0.10028244211278005)),
 (371, np.float64(0.10028244211278005)),
 (412, np.float64(0.10028244211278005)),
 (473, np.float64(0.10028244211278005)),
 (870, np.float64(0.10028244211278005)),
 (1200, np.float64(0.10028244211278005)),
 (1435, np.float64(0.10028244211278005)),
 (410, np.float64(0.09913631941932194)),
 (813, np.float64(0.09913631941932194)),
 (933, np.float64(0.09913631941932194)),
 (1274, np.float64(0.09913631941932194)),
 (1842, np.float64(0.09913631941932194)),
 (2280, np.float64(0.09913631941932194)),
 (292, np.float64(0.09863939238321438)),
 (389, np.float64(0.09863939238321438)),
 (530, np.float64(0.09863939238321438)),
 (691, np.float64(0.09863939238321438)),
 (791, np.float64(0.09863939238321438)),
 (1075, np.float64(0.09863939238321438)),
 (1404, np.float64(0.09863939238321438)),
 (2647, np.float64(0.09863939238321438)),
 (3734, np.float64(0.09863939238321438)),
 (1819, np.float64(0.09802861627917438)),
 (1999, np.float64(0.09802861627917438)),
 (1087, np.float64(0.09755285137982107)),
 (243, np.float64(0.09695723311274393)),
 (785, np.float64(0.09687303228651607)),
 (122, np.float64(0.09672388203287416)),
 (564, np.float64(0.09672388203287416)),
 (1470, np.float64(0.09672388203287416)),
 (1585, np.float64(0.09672388203287416)),
 (1682, np.float64(0.09672388203287416)),
 (1752, np.float64(0.09672388203287416)),
 (2648, np.float64(0.09672388203287416)),
 (3091, np.float64(0.09672388203287416)),
 (589, np.float64(0.09592022754223367)),
 (618, np.float64(0.09592022754223367)),
 (1355, np.float64(0.09592022754223367)),
 (43, np.float64(0.09491579957524991)),
 (2792, np.float64(0.09491579957524991)),
 (3152, np.float64(0.09491579957524991)),
 (12, np.float64(0.0949157995752499)),
 (23, np.float64(0.0949157995752499)),
 (142, np.float64(0.0949157995752499)),
 (236, np.float64(0.0949157995752499)),
 (362, np.float64(0.0949157995752499)),
 (1025, np.float64(0.0949157995752499)),
 (2089, np.float64(0.0949157995752499)),
 (2392, np.float64(0.0949157995752499)),
 (206, np.float64(0.09428928580058928)),
 (1414, np.float64(0.09394227846020416)),
 (160, np.float64(0.09367501681349609)),
 (511, np.float64(0.09320546490018)),
 (922, np.float64(0.09320546490018)),
 (1002, np.float64(0.09320546490018)),
 (2813, np.float64(0.09320546490018)),
 (2836, np.float64(0.09320546490018)),
 (3426, np.float64(0.09320546490018)),
 (596, np.float64(0.09299811099505542)),
 (1920, np.float64(0.09299811099505542)),
 (2484, np.float64(0.09299811099505542)),
 (479, np.float64(0.09248165577087424)),
 (1276, np.float64(0.09208185110322616)),
 (1828, np.float64(0.09208185110322616)),
 (164, np.float64(0.09158437663089954)),
 (21, np.float64(0.09158437663089952)),
 (242, np.float64(0.09158437663089952)),
 (306, np.float64(0.09158437663089952)),
 (794, np.float64(0.09158437663089952)),
 (960, np.float64(0.09158437663089952)),
 (978, np.float64(0.09158437663089952)),
 (1247, np.float64(0.09158437663089952)),
 (1519, np.float64(0.09158437663089952)),
 (4468, np.float64(0.09158437663089952)),
 (799, np.float64(0.09133277072519848)),
 (1492, np.float64(0.09119215051751065)),
 (2270, np.float64(0.09119215051751065)),
 (2384, np.float64(0.09119215051751065)),
 (2852, np.float64(0.09119215051751065)),
 (4353, np.float64(0.09119215051751065)),
 (4502, np.float64(0.09119215051751065)),
 (4516, np.float64(0.09119215051751065)),
 (4654, np.float64(0.09119215051751065)),
 (2444, np.float64(0.09077415526644964)),
 (2966, np.float64(0.09032775043542898)),
 (75, np.float64(0.09004503377814962)),
 (112, np.float64(0.09004503377814962)),
 (227, np.float64(0.09004503377814962)),
 (349, np.float64(0.09004503377814962)),
 (775, np.float64(0.09004503377814962)),
 (901, np.float64(0.09004503377814962)),
 (1374, np.float64(0.09004503377814962)),
 (1696, np.float64(0.09004503377814962)),
 (1786, np.float64(0.09004503377814962)),
 (2163, np.float64(0.09004503377814962)),
 (3447, np.float64(0.09004503377814962)),
 (3535, np.float64(0.09004503377814962)),
 (4626, np.float64(0.09004503377814962)),
 (170, np.float64(0.08948747402853657)),
 (812, np.float64(0.08948747402853657)),
 (2001, np.float64(0.08948747402853657)),
 (32, np.float64(0.08867021970429453)),
 (107, np.float64(0.08867021970429453)),
 (222, np.float64(0.08867021970429453)),
 (467, np.float64(0.08867021970429453)),
 (541, np.float64(0.08867021970429453)),
 (2494, np.float64(0.08867021970429453)),
 (1, np.float64(0.0885807893036239)),
 (88, np.float64(0.0885807893036239)),
 (121, np.float64(0.0885807893036239)),
 (245, np.float64(0.0885807893036239)),
 (315, np.float64(0.0885807893036239)),
 (786, np.float64(0.0885807893036239)),
 (894, np.float64(0.0885807893036239)),
 (3299, np.float64(0.0885807893036239)),
 (3814, np.float64(0.0885807893036239)),
 (45, np.float64(0.08787495503274936)),
 (230, np.float64(0.08787495503274936)),
 (363, np.float64(0.08787495503274936)),
 (381, np.float64(0.08787495503274936)),
 (1137, np.float64(0.08787495503274936)),
 (2876, np.float64(0.08787495503274936)),
 (4163, np.float64(0.08787495503274936)),
 (4737, np.float64(0.08787495503274936)),
 (2382, np.float64(0.0876249546540977)),
 (86, np.float64(0.08718572905786445)),
 (96, np.float64(0.08718572905786445)),
 (98, np.float64(0.08718572905786445)),
 (356, np.float64(0.08718572905786445)),
 (937, np.float64(0.08718572905786445)),
 (1111, np.float64(0.08718572905786445)),
 (1140, np.float64(0.08718572905786445)),
 (1267, np.float64(0.08718572905786445)),
 (2243, np.float64(0.08718572905786445)),
 (2247, np.float64(0.08718572905786445)),
 (2300, np.float64(0.08718572905786445)),
 (3089, np.float64(0.08718572905786445)),
 (4257, np.float64(0.08718572905786445)),
 (4657, np.float64(0.08718572905786445)),
 (654, np.float64(0.08710071126186844)),
 (1874, np.float64(0.08710071126186844)),
 (103, np.float64(0.0863465783552691)),
 (1280, np.float64(0.0863465783552691)),
 (39, np.float64(0.08585457105482137)),
 (101, np.float64(0.08585457105482137)),
 (203, np.float64(0.08585457105482137)),
 (457, np.float64(0.08585457105482137)),
 (547, np.float64(0.08585457105482137)),
 (814, np.float64(0.08585457105482137)),
 (899, np.float64(0.08585457105482137)),
 (1205, np.float64(0.08585457105482137)),
 (1469, np.float64(0.08585457105482137)),
 (2790, np.float64(0.08585457105482137)),
 (3308, np.float64(0.08585457105482137)),
 (193, np.float64(0.08561170049453902)),
 (501, np.float64(0.08561170049453902)),
 (1824, np.float64(0.08561170049453902)),
 (491, np.float64(0.08489527199560176)),
 (1401, np.float64(0.08489527199560176)),
 (2161, np.float64(0.08489527199560176)),
 (2246, np.float64(0.08489527199560176)),
 (3067, np.float64(0.08489527199560176)),
 (3439, np.float64(0.08489527199560176)),
 (4492, np.float64(0.08489527199560176)),
 (4718, np.float64(0.08489527199560176)),
 (257, np.float64(0.08458258116519013)),
 (626, np.float64(0.08458258116519013)),
 (746, np.float64(0.08458258116519013)),
 (787, np.float64(0.08458258116519013)),
 (3026, np.float64(0.08458258116519013)),
 (3138, np.float64(0.08458258116519013)),
 (3233, np.float64(0.08458258116519013)),
 (3421, np.float64(0.08458258116519013)),

In [33]:
new_df = movies[['movie_id', 'title', 'tags']]

In [34]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [35]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [36]:
recommend('Avatar')

Titan A.E.
Small Soldiers
Ender's Game
Aliens vs Predator: Requiem
Independence Day

In [37]:
recommend('Spider-Man')

Spider-Man 3
Spider-Man 2
The Amazing Spider-Man 2
The Amazing Spider-Man
Arachnophobia

In [38]:
import pickle

In [39]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [40]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [41]:
pickle.dump(new_df.to_dict(), open('movie_dict.pkl', 'wb'))

In [42]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))